#!/bin/bash
set -e
if [ -z "$1" ]; then
    echo "Usage: $0 <version>"
    exit 1
fi

PROJECT=exile
REPO=ehazlett/$PROJECT
VERSION=$1

if [ -z "$GITHUB_TOKEN" ]; then
    echo "GITHUB_TOKEN must be set for github-release"
    exit 1
fi

echo "Building"
script/build $VERSION

echo "Pushing to Hub"
docker tag -f $REPO:$VERSION ehazlett/certm:latest
docker push $REPO:$VERSION
docker push $REPO:latest

echo "Generating sums"
docker run --rm -v `pwd`:/go/src/github.com/$REPO $PROJECT-build ./script/generate-sums

echo "Creating Tag"
git tag $VERSION
echo "Pushing tag"
git push --tags

echo "Creating Release"
docker run --rm -e GITHUB_TOKEN $PROJECT-build github-release release \
    --user ehazlett \
    --repo $PROJECT \
    --tag $VERSION \
    --name $VERSION \
    --description "" \
    --pre-release

for BINARY in $PROJECT_*; do
    echo "Uploading $BINARY"
    docker run --rm -e GITHUB_TOKEN -v `pwd`:/go/src/github.com/ehazlett/$PROJECT \
        $PROJECT-build github-release upload \
        --user ehazlett \
        --repo $PROJECT \
        --tag $VERSION \
        --name $BINARY \
        --file $BINARY
done
